[pytest]
python_files = *test.py *test*.py test*.py
#здесь прописать маски файлов, например: *abc.py
; python_files = test_string_utils.py
; python_files = 
;     test_lesson05_task1.py
;     test_lesson05_task2.py
;     test_lesson05_task3.py
;     test_lesson06_task1.py
;     test_lesson06_task2.py
python_functions = test_*
markers = pozitive negativ
addopts = -v -s